### ISSUE TITLE
Morning Session :Peer to Peer Code Review 

### ISSUE THREAD

**Issue by abenezer-addisu** [Nahid1911/WebPack_To_Do_List#4]
Hi @Nahid1911 👋,

**Good job so far!**

<img src="https://media0.giphy.com/media/XreQmk7ETCak0/giphy.gif"/>

Highlights 🌟
✔️ Descriptions are very descriptive
✔️ Linters checks are passing
✔️ Use GitHub Flow
✔️ Meaningful commit messages.
✔️ All errors are Fixed

There are some issues but you are almost Done! 🏃‍♂️ 🏃

- [ ] Add live Demo link

Cheers, and Happy coding!👏👏👏

**Comment by faisalakb** [comment]
Your work is excellent.

**Comment by MenendezON** [comment]
Good job so far.
